// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

function Footer(Props) {
  var logoOpt = Props.logo;
  var logo = logoOpt !== undefined ? Caml_option.valFromOption(logoOpt) : null;
  return React.createElement("footer", {
              className: "flex py-12 px-28 justify-between items-center bg-black text-white"
            }, React.createElement("div", {
                  className: "flex flex-col gap-y-6"
                }, logo, React.createElement("p", {
                      className: ""
                    }, "Send anything, anywhere, anytime")));
}

var make = Footer;

var $$default = Footer;

export {
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
