// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function AboutUsHeader(Props) {
  var title = Props.title;
  return React.createElement("div", {
              className: "bg-black text-white text-center flex w-full py-11"
            }, React.createElement("p", {
                  className: "m-auto uppercase text-4xl font-bold"
                }, title));
}

var make = AboutUsHeader;

var $$default = AboutUsHeader;

export {
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
