// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Array from "rescript/lib/es6/array.js";
import * as React from "react";

function AboutUsHeroSection(Props) {
  var rows = Props.rows;
  return React.createElement("div", {
              className: "bg-white flex w-full py-8 xl:px-28 px-24"
            }, React.createElement("div", {
                  className: "flex flex-col gap-y-10"
                }, $$Array.mapi((function (index, row) {
                        var reverseRow = index % 2 === 0;
                        return React.createElement("div", {
                                    key: String(index),
                                    className: "flex " + (
                                      reverseRow ? "flex-row" : "flex-row-reverse"
                                    ) + " justify-between items-center"
                                  }, React.createElement("p", {
                                        className: "w-1/2"
                                      }, row.description), React.createElement("img", {
                                        className: "object-cover",
                                        height: "300",
                                        src: row.image,
                                        width: "500"
                                      }));
                      }), rows)));
}

var make = AboutUsHeroSection;

var $$default = AboutUsHeroSection;

export {
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
