// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Array from "rescript/lib/es6/array.js";
import * as React from "react";

function AboutUsStatsSection(Props) {
  var statsData = Props.statsData;
  return React.createElement("div", {
              className: "flex flex-col py-8 px-24 justify-center items-center"
            }, React.createElement("p", {
                  className: "text-2xl"
                }, statsData.title), React.createElement("div", {
                  className: "w-7 h-1 bg-primary mt-7 mb-5 rounded"
                }), React.createElement("div", {
                  className: "flex gap-x-20"
                }, $$Array.map((function (statItem) {
                        return React.createElement("div", {
                                    className: "flex flex-col items-center"
                                  }, React.createElement("h1", {
                                        className: "text-4xl font-bold"
                                      }, statItem.count), React.createElement("p", {
                                        className: "font-semibold"
                                      }, statItem.label));
                      }), statsData.statItems)));
}

var make = AboutUsStatsSection;

var $$default = AboutUsStatsSection;

export {
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
