// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Button$PorterCore from "../../../components/button/Button.mjs";

function JoinPorterSection(Props) {
  var data = Props.data;
  var onJoinPorterClick = function (param) {
    console.log("Redirect to Career Page");
    
  };
  return React.createElement("div", {
              className: "flex flex-col py-8  "
            }, React.createElement("img", {
                  className: "w-full",
                  height: "420",
                  src: data.image
                }), React.createElement("div", {
                  className: "flex flex-col justify-center items-center py-10"
                }, React.createElement("h2", {
                      className: "text-3xl font-bold"
                    }, data.title), React.createElement("p", {
                      className: "mt-4 mb-8"
                    }, data.subTitle), React.createElement(Button$PorterCore.make, {
                      label: data.buttonLabel,
                      onClick: onJoinPorterClick,
                      classOverride: "px-6 py-4"
                    })));
}

var make = JoinPorterSection;

var $$default = JoinPorterSection;

export {
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
