// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Button(Props) {
  var label = Props.label;
  var onClickOpt = Props.onClick;
  var variantOpt = Props.variant;
  var classOverrideOpt = Props.classOverride;
  var onClick = onClickOpt !== undefined ? onClickOpt : (function (param) {
        
      });
  var variant = variantOpt !== undefined ? variantOpt : /* PRIMARY */0;
  var classOverride = classOverrideOpt !== undefined ? classOverrideOpt : "";
  var buttonClasses;
  switch (variant) {
    case /* PRIMARY */0 :
        buttonClasses = "bg-primary";
        break;
    case /* SECONDARY */1 :
        buttonClasses = "bg-white border border-gray-300 text-black hover:border-primary";
        break;
    case /* TERTIARY */2 :
        buttonClasses = "bg-transparent p-0 m-0 text-black hover:text-primary";
        break;
    
  }
  return React.createElement("button", {
              className: "px-4 py-2 rounded text-white " + buttonClasses + " " + classOverride,
              onClick: onClick
            }, label);
}

var make = Button;

var $$default = Button;

export {
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
