// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Array from "rescript/lib/es6/array.js";
import * as React from "react";
import * as Caml_option from "rescript/lib/es6/caml_option.js";

function Header(Props) {
  var logoOpt = Props.logo;
  var navItems = Props.navItems;
  var rightNavItems = Props.rightNavItems;
  var logo = logoOpt !== undefined ? Caml_option.valFromOption(logoOpt) : null;
  return React.createElement("header", {
              className: "flex justify-between items-center px-48 h-16 sticky top-0 bg-white"
            }, logo, React.createElement("nav", undefined, React.createElement("ul", {
                      className: "flex gap-x-6"
                    }, $$Array.map((function (nav) {
                            var label = nav.label;
                            return React.createElement("li", {
                                        key: label,
                                        className: "hover:underline decoration-primary underline-offset-4 "
                                      }, React.createElement("a", {
                                            className: "font-semibold",
                                            href: nav.redirectTo
                                          }, label));
                          }), navItems))), React.createElement("nav", undefined, React.createElement("ul", {
                      className: "flex gap-x-6"
                    }, $$Array.map((function (nav) {
                            return React.createElement("li", {
                                        className: "hover:underline decoration-primary underline-offset-4 "
                                      }, React.createElement("a", {
                                            className: "font-semibold",
                                            href: nav.redirectTo
                                          }, nav.label));
                          }), rightNavItems))));
}

var make = Header;

var $$default = Header;

export {
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
