// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as AboutUsHeader$PorterCore from "./components/AboutUsHeader.mjs";
import * as JoinPorterSection$PorterCore from "./components/JoinPorterSection.mjs";
import * as AboutUsHeroSection$PorterCore from "./components/AboutUsHeroSection.mjs";
import * as AboutUsStatsSection$PorterCore from "./components/AboutUsStatsSection.mjs";

function AboutUsLayout(Props) {
  var data = Props.data;
  return React.createElement("div", {
              className: "flex flex-col w-full xl:mx-20 lg:mx-0"
            }, React.createElement(AboutUsHeader$PorterCore.make, {
                  title: "About Us"
                }), React.createElement(AboutUsHeroSection$PorterCore.make, {
                  rows: data.rows
                }), React.createElement(AboutUsStatsSection$PorterCore.make, {
                  statsData: data.stats
                }), React.createElement(JoinPorterSection$PorterCore.make, {
                  data: data.joinPorterSection
                }));
}

var make = AboutUsLayout;

var $$default = AboutUsLayout;

export {
  make ,
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
